theme: jekyll-theme-minimal
title: Nihon Turismo
logo: /assets/images/nihonturismo.svg
description: Nihon Turismo is a collection of pre-existing roads originally created by talented artists for various commercial and hobbyist driving software; modified, expanded and compiled into a single driveable environment for Assetto Corsa. Created without permission but with gratitude. {% include youtube.html id="V3jng03abW8" %} 
show_downloads: false
